#!/usr/bin/env python
import cgi, os
import cgitb

cgitb.enable()
form = cgi.FieldStorage()
print 'Content-Type: text/html'
print
print '<!DOCTYPE html>'
print '<html>'
print '<head>'
print '<style>'
print '.pagination {'
print '     display: inline-block;'
print '}'
print ''
print '.pagination a {'
print '    color: black;'
print '    float: left;'
print '    padding: 8px 16px;'
print '    text-decoration: none;'
print '}'
print '.pagination a.active {'
print '    background-color: #4CAF50;'
print '    color: white;'
print '}'
print ''
print '.pagination a:hover:not(.active) {background-color: #ddd;}'
print '</style>'
print '</head>'
print '<body>'
print '<h2>Active and Hoverable Pagination</h2>'
print '<p>Move the mouse over the numbers.</p>'
print '<div class="pagination">'
print '  <a href="#">&laquo;</a>'
print '  <a href="#">1</a>'
print '  <a class="active" href="#">2</a>'
print '  <a href="#">3</a>'
print '  <a href="#">4</a>'
print '  <a href="#">5</a>'
print '  <a href="#">6</a>'
print '  <a href="#">&raquo;</a>'
print '</div>'
print '</body>'
print '</html>'
